# Importing modules

In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pylab

In [5]:
nypd=pd.read_csv("F:/python/csv/nypd_all_data.csv")

In [6]:
nypd

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,173130602,12/31/2017,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,105,0.0,25-44,M,BLACK,1063056.0,207463.0,40.735772,-73.715638
1,173114463,12/31/2017,478.0,"THEFT OF SERVICES, UNCLASSIFIED",343.0,OTHER OFFENSES RELATED TO THEFT,PL 1651503,M,Q,114,0.0,25-44,M,ASIAN / PACIFIC ISLANDER,1009113.0,219613.0,40.769437,-73.910241
2,173113513,12/31/2017,849.0,"NY STATE LAWS,UNCLASSIFIED VIOLATION",677.0,OTHER STATE LAWS,LOC000000V,V,K,73,1.0,18-24,M,BLACK,1010719.0,186857.0,40.679525,-73.904572
3,173113423,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,0.0,25-44,M,WHITE,987831.0,217446.0,40.763523,-73.987074
4,173113421,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,0.0,45-64,M,BLACK,987073.0,216078.0,40.759768,-73.989811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798334,173142136,01/01/2018,639.0,AGGRAVATED HARASSMENT 2,361.0,OFF. AGNST PUB ORD SENSBLTY & RGHTS TO PRIV,PL 2403002,M,B,41,0.0,25-44,F,WHITE HISPANIC,1013086.0,236614.0,40.816088,-73.895824
4798335,173135232,01/01/2018,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,B,44,0.0,25-44,M,BLACK HISPANIC,1007649.0,243339.0,40.834562,-73.915443
4798336,173134328,01/01/2018,397.0,"ROBBERY,UNCLASSIFIED,OPEN AREAS",105.0,ROBBERY,PL 1601503,F,M,10,0.0,45-64,M,BLACK,983620.0,208914.0,40.740105,-74.002275
4798337,173134322,01/01/2018,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,M,30,0.0,25-44,M,BLACK HISPANIC,998981.0,242209.0,40.831479,-73.946770
4798338,173130592,01/01/2018,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200512,F,K,70,0.0,45-64,M,BLACK HISPANIC,995824.0,170921.0,40.635816,-73.958301

# Length of file

In [7]:
len(nypd)

4798339

# Filling na values with 0

In [21]:
nypd=nypd.fillna(0)

# Replacing 0 with NAN

In [36]:
import numpy as np
nypd=nypd.replace(['0',' ' ,'-'],np.NAN)

In [37]:
nypd_empty=nypd.isnull().values.any()
nypd_empty

True

In [29]:
nypd_empty=nypd.isnull()
nypd_empty

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798334,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4798335,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4798336,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4798337,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4798338,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False

In [38]:
nypd

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,173130602,12/31/2017,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,105,NaN,25-44,M,BLACK,1063056.0,207463.0,40.735772,-73.715638
1,173114463,12/31/2017,478.0,"THEFT OF SERVICES, UNCLASSIFIED",343.0,OTHER OFFENSES RELATED TO THEFT,PL 1651503,M,Q,114,NaN,25-44,M,ASIAN / PACIFIC ISLANDER,1009113.0,219613.0,40.769437,-73.910241
2,173113513,12/31/2017,849.0,"NY STATE LAWS,UNCLASSIFIED VIOLATION",677.0,OTHER STATE LAWS,LOC000000V,V,K,73,1.0,18-24,M,BLACK,1010719.0,186857.0,40.679525,-73.904572
3,173113423,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,NaN,25-44,M,WHITE,987831.0,217446.0,40.763523,-73.987074
4,173113421,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,NaN,45-64,M,BLACK,987073.0,216078.0,40.759768,-73.989811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798334,173142136,01/01/2018,639.0,AGGRAVATED HARASSMENT 2,361.0,OFF. AGNST PUB ORD SENSBLTY & RGHTS TO PRIV,PL 2403002,M,B,41,NaN,25-44,F,WHITE HISPANIC,1013086.0,236614.0,40.816088,-73.895824
4798335,173135232,01/01/2018,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,B,44,NaN,25-44,M,BLACK HISPANIC,1007649.0,243339.0,40.834562,-73.915443
4798336,173134328,01/01/2018,397.0,"ROBBERY,UNCLASSIFIED,OPEN AREAS",105.0,ROBBERY,PL 1601503,F,M,10,NaN,45-64,M,BLACK,983620.0,208914.0,40.740105,-74.002275
4798337,173134322,01/01/2018,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL0511001,M,M,30,NaN,25-44,M,BLACK HISPANIC,998981.0,242209.0,40.831479,-73.946770
4798338,173130592,01/01/2018,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200512,F,K,70,NaN,45-64,M,BLACK HISPANIC,995824.0,170921.0,40.635816,-73.958301

# Grouping by

In [43]:
grouping=nypd.groupby('PD_DESC')
grouping

In [46]:
assault=grouping.get_group('ASSAULT 3' )
assault

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
3,173113423,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,NaN,25-44,M,WHITE,987831.0,217446.0,40.763523,-73.987074
4,173113421,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,18,NaN,45-64,M,BLACK,987073.0,216078.0,40.759768,-73.989811
6,173129349,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,9,NaN,18-24,F,WHITE HISPANIC,990592.0,202391.0,40.722199,-73.977122
8,173128437,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,23,2.0,25-44,M,BLACK HISPANIC,998165.0,226184.0,40.787496,-73.949752
10,173128430,12/31/2017,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200002,M,K,83,NaN,25-44,M,WHITE HISPANIC,1003807.0,195345.0,40.702840,-73.929467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798281,173135246,01/01/2018,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,115,NaN,<18,M,WHITE HISPANIC,1014152.0,214701.0,40.755939,-73.892071
4798286,173133807,01/01/2018,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,52,NaN,25-44,M,WHITE HISPANIC,1011095.0,253282.0,40.861843,-73.902951
4798287,173132273,01/01/2018,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,30,NaN,18-24,M,WHITE HISPANIC,997227.0,238083.0,40.820157,-73.953116
4798307,173148108,01/01/2018,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,44,NaN,45-64,F,WHITE HISPANIC,1004352.0,244652.0,40.838174,-73.927354
4798314,173134305,01/01/2018,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,46,NaN,45-64,M,BLACK,1005725.0,249742.0,40.852141,-73.922376

In [47]:
assault1=grouping.get_group('MARIJUANA, POSSESSION')
assault1

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
0,173130602,12/31/2017,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,105,NaN,25-44,M,BLACK,1063056.0,207463.0,40.735772,-73.715638
859,173093592,12/29/2017,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,114,NaN,25-44,M,BLACK,1002895.0,220799.0,40.772707,-73.932686
1125,173067176,12/29/2017,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,M,34,NaN,18-24,M,WHITE HISPANIC,1004148.0,254866.0,40.866209,-73.928061
1357,173085773,12/29/2017,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,K,75,NaN,25-44,M,BLACK,1021004.0,181754.0,40.665481,-73.867518
2891,172980826,12/26/2017,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,K,77,NaN,25-44,M,BLACK,1000498.0,186135.0,40.677568,-73.941424
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795395,173303981,01/06/2018,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,101,NaN,18-24,M,BLACK,1053994.0,162151.0,40.611477,-73.748806
4795759,173294930,01/05/2018,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,M,33,NaN,18-24,M,BLACK HISPANIC,1001409.0,246594.0,40.843510,-73.937985
4796649,173200154,01/03/2018,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,K,61,NaN,18-24,M,WHITE,997625.0,158473.0,40.601646,-73.951836
4797305,173172265,01/02/2018,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,106,NaN,18-24,M,WHITE HISPANIC,1030214.0,186661.0,40.678907,-73.834287
4797629,173184333,01/02/2018,566.0,"MARIJUANA, POSSESSION",678.0,MISCELLANEOUS PENAL LAW,PL 2210500,V,Q,105,NaN,25-44,M,WHITE HISPANIC,1053945.0,196635.0,40.706128,-73.748626

In [75]:
Drp=nypd.drop(columns=['KY_CD','ARREST_KEY','LAW_CODE','LAW_CAT_CD','ARREST_BORO','ARREST_PRECINCT','PD_CD','X_COORD_CD','Y_COORD_CD'])

In [76]:
Drp

,ARREST_DATE,PD_DESC,OFNS_DESC,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude
0,12/31/2017,"MARIJUANA, POSSESSION",MISCELLANEOUS PENAL LAW,NaN,25-44,M,BLACK,40.735772,-73.715638
1,12/31/2017,"THEFT OF SERVICES, UNCLASSIFIED",OTHER OFFENSES RELATED TO THEFT,NaN,25-44,M,ASIAN / PACIFIC ISLANDER,40.769437,-73.910241
2,12/31/2017,"NY STATE LAWS,UNCLASSIFIED VIOLATION",OTHER STATE LAWS,1.0,18-24,M,BLACK,40.679525,-73.904572
3,12/31/2017,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,NaN,25-44,M,WHITE,40.763523,-73.987074
4,12/31/2017,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,NaN,45-64,M,BLACK,40.759768,-73.989811
...,...,...,...,...,...,...,...,...,...
4798334,01/01/2018,AGGRAVATED HARASSMENT 2,OFF. AGNST PUB ORD SENSBLTY & RGHTS TO PRIV,NaN,25-44,F,WHITE HISPANIC,40.816088,-73.895824
4798335,01/01/2018,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,NaN,25-44,M,BLACK HISPANIC,40.834562,-73.915443
4798336,01/01/2018,"ROBBERY,UNCLASSIFIED,OPEN AREAS",ROBBERY,NaN,45-64,M,BLACK,40.740105,-74.002275
4798337,01/01/2018,"TRAFFIC,UNCLASSIFIED MISDEMEAN",VEHICLE AND TRAFFIC LAWS,NaN,25-44,M,BLACK HISPANIC,40.831479,-73.946770
4798338,01/01/2018,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,NaN,45-64,M,BLACK HISPANIC,40.635816,-73.958301

In [77]:
group_by_date=Drp.groupby('ARREST_DATE')

In [78]:
group_by_date.get_group('12/31/2017')

,ARREST_DATE,PD_DESC,OFNS_DESC,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude
0,12/31/2017,"MARIJUANA, POSSESSION",MISCELLANEOUS PENAL LAW,NaN,25-44,M,BLACK,40.735772,-73.715638
1,12/31/2017,"THEFT OF SERVICES, UNCLASSIFIED",OTHER OFFENSES RELATED TO THEFT,NaN,25-44,M,ASIAN / PACIFIC ISLANDER,40.769437,-73.910241
2,12/31/2017,"NY STATE LAWS,UNCLASSIFIED VIOLATION",OTHER STATE LAWS,1.0,18-24,M,BLACK,40.679525,-73.904572
3,12/31/2017,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,NaN,25-44,M,WHITE,40.763523,-73.987074
4,12/31/2017,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,NaN,45-64,M,BLACK,40.759768,-73.989811
...,...,...,...,...,...,...,...,...,...
348,12/31/2017,"MARIJUANA, POSSESSION 4 & 5",DANGEROUS DRUGS,NaN,25-44,M,BLACK,40.612940,-74.087488
349,12/31/2017,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,NaN,45-64,M,WHITE HISPANIC,40.702840,-73.929467
350,12/31/2017,"PUBLIC ADMINISTRATION,UNCLASSIFIED FELONY",MISCELLANEOUS PENAL LAW,NaN,25-44,M,WHITE,40.579732,-73.959776
351,12/31/2017,STRANGULATION 1ST,FELONY ASSAULT,NaN,18-24,M,BLACK,40.737972,-73.884013
352,12/31/2017,"WEAPONS, POSSESSION, ETC",DANGEROUS WEAPONS,NaN,45-64,M,BLACK,40.816089,-73.917689

In [80]:
grp_by_sex=Drp.groupby('PERP_SEX')

In [81]:
grp_by_sex

In [82]:
grp_by_sex.get_group('M')

,ARREST_DATE,PD_DESC,OFNS_DESC,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude
0,12/31/2017,"MARIJUANA, POSSESSION",MISCELLANEOUS PENAL LAW,NaN,25-44,M,BLACK,40.735772,-73.715638
1,12/31/2017,"THEFT OF SERVICES, UNCLASSIFIED",OTHER OFFENSES RELATED TO THEFT,NaN,25-44,M,ASIAN / PACIFIC ISLANDER,40.769437,-73.910241
2,12/31/2017,"NY STATE LAWS,UNCLASSIFIED VIOLATION",OTHER STATE LAWS,1.0,18-24,M,BLACK,40.679525,-73.904572
3,12/31/2017,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,NaN,25-44,M,WHITE,40.763523,-73.987074
4,12/31/2017,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,NaN,45-64,M,BLACK,40.759768,-73.989811
...,...,...,...,...,...,...,...,...,...
4798333,01/01/2018,"LARCENY,PETIT FROM OPEN AREAS,UNCLASSIFIED",PETIT LARCENY,NaN,25-44,M,BLACK,40.887333,-73.847250
4798335,01/01/2018,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,NaN,25-44,M,BLACK HISPANIC,40.834562,-73.915443
4798336,01/01/2018,"ROBBERY,UNCLASSIFIED,OPEN AREAS",ROBBERY,NaN,45-64,M,BLACK,40.740105,-74.002275
4798337,01/01/2018,"TRAFFIC,UNCLASSIFIED MISDEMEAN",VEHICLE AND TRAFFIC LAWS,NaN,25-44,M,BLACK HISPANIC,40.831479,-73.946770
4798338,01/01/2018,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,NaN,45-64,M,BLACK HISPANIC,40.635816,-73.958301

In [105]:
import matplotlib.pyplot as plt
%matplotlib inline

In [107]:
Drp.to_csv('file1.csv')